config/routes.rb
Rails.application.routes.draw do

  resources :accounts

 
  

end

app/models/account.rb
class Account < ActiveRecord::Base
  self.table_name = "salesforce.account"
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  self.table_name = "salesforce.contact"
  
end

app/models/triggerlog.rb
class Triggerlog < ActiveRecord::Base
  self.table_name = "salesforce._trigger_log"
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all.order('id DESC')
    @triggerlog = Triggerlog.last
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit

  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    
    
    # we need to force a simple account type
    #@account.recordtypeid = "012F0000001HoUaIAK"

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params[:account].permit(:name, :tickersymbol, :phone, :website, :billingstreet, :billingcity, :billingstate, :billingpostalcode, :billingcountry )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params[:contact]
    end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/accounts/_form.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">

<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="table">
<tr>
	<td>Name: </td>
	<td><%= f.text_field :name %></td>
</tr>
<tr>
	<td>Ticker Symbol: </td>
	<td><%= f.text_field :tickersymbol %></td>
</tr>
<tr>
	<td>Phone Number: </td>
	<td><%= f.text_field :phone  %></td>
</tr>
<tr>
	<td>Website: </td>
	<td><%= f.text_field :website %></td>
</tr>
<tr>
	<td>Street Address: </td>
	<td><%= f.text_field :billingstreet %></td>
</tr>
<tr>
	<td>City: </td>
	<td><%= f.text_field :billingcity %></td>
</tr>
<tr>
	<td>State: </td>
	<td><%= f.text_field :billingstate %></td>
</tr>
<tr>
	<td>Postal Code: </td>
	<td><%= f.text_field :billingpostalcode %></td>
</tr>
<tr>
	<td>Country</td>
	<td><%= f.text_field :billingcountry %></td>
</tr>
</table>


</br>
</br>

  <div class="center">    
      <div class="btn btn-default">
          <%= f.submit %>
      </div>
  </div>
</br>
<% end %>

</div>
</div>

app/views/accounts/edit.html.erb
<h1>Editing <%= @account.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'List All Accounts', accounts_path %> |
<%= link_to 'Destroy', @account, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/accounts/index.html.erb
<div class="center">

<h1>Listing Accounts from Salesforce Org</h1>

</div>

</br>
</br>

<div id=.button ><%= link_to 'Create New Account', new_account_path %></div>

</br>
</br>

<table class="table">
  <thead>
    <tr>
      <th>Account Name</th>
      <th>Website</th>
      <th>City</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
		<!--<td><%= account.id %></td>-->
		<td><%= link_to account.name, account %></td>
		<td><a href="http://<%= account.website %>"><%= account.website %></a></td>
		<td><%= account.billingcity %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
      </tr>
    <% end %>
  </tbody>
</div>
</table>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
<tr>
	<td>Name: </td>
	<td><%= @account.name %></td>
</tr>
<tr>
	<td>Ticker Symbol: </td>
	<td><%= @account.tickersymbol %></td>
</tr>
<tr>
	<td>Phone Number: </td>
	<td><%= @account.phone %></td>
</tr>
<tr>
	<td>Website: </td>
	<td><a href=<%= @account.website %>><%= @account.website %></a></td>
</tr>
<tr>
	<td>Street Address: </td>
	<td><%= @account.billingstreet %></td>
</tr>
<tr>
	<td>City: </td>
	<td><%= @account.billingcity %></td>
</tr>
<tr>
	<td>State: </td>
	<td><%= @account.billingstate %></td>
</tr>
<tr>
	<td>Postal Code: </td>
	<td><%= @account.billingpostalcode %></td>
</tr>
<tr>
	<td>Country: </td>
	<td><%= @account.billingcountry %></td>
</tr>
<tr>
	<td>Description: </td>
	<td><%= @account.description %></td>
</tr>
<tr>
	<td>Last Modified: </td>
	<td><%= @account.lastmodifieddate %></td>
</tr>
</table>
<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'List All Accounts', accounts_path %>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConnectDemoApp</title>
  
         <link rel="stylesheet" href="/css/style.css" type="text/css" media="screen" title="no title" charset="utf-8">
         <link rel="stylesheet" href="/css/purple.css" type="text/css" media="screen" title="no title" charset="utf-8">
        <script src="/js/purple.js" type="text/javascript" charset="utf-8"></script>
        <%= csrf_meta_tags %>
</head>
<body>
	<header id="header" class="gradient-primary">
		<div class="container text-center">
			<div class="title">Account List</div>
            </div>
        </div>
    </header>
        <div id="content" class="container">
            <%= yield %>
        </div>
</body>
</html>